baseURL = "https://blog.steamedfish.org"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
title = "SteamedFish's BLOG"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
#theme = "toha"
enableGitInfo = false
hasCJKLanguage = true
enableMissingTranslationPlaceholders = false
copyright = "SteamedFish's BLOG"
paginate = 10
timeZone = "Asia/Shanghai"
sectionPagesMenu = 'main'

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        enable = true
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
      [markup.goldmark.renderer]
        unsafe = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_inline = false
    lineNos = true
    lineNumbersInTable = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[module]
  [[module.imports]]
    path = 'github.com/hugo-toha/toha/v4'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = './node_modules/flag-icon-css/flags'
    target = 'static/flags'
  [[module.mounts]]
    source = './node_modules/@fontsource/mulish/files'
    target = 'static/files'
  [[module.mounts]]
    source = './node_modules/katex/dist/fonts'
    target = 'static/fonts'

